kind: pipeline
type: docker
name: hello-world

steps:
- name: docker  
  image: plugins/docker
  settings:
    registry: https://index.docker.io/v2/
    repo: shahidahmad/dronepush
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags: 
      - latest
